import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Box, Toolbar } from "@mui/material"
import MainNav from "./components/nav/MainNav"
import { cookies } from "next/headers"
import db from "./connect"
import AppWrapper from "./components/AppWrapper"

const inter = Inter({ subsets: ["latin"] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = cookies()
  // const user = useUser()
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppWrapper>
          <MainNav />
          <main>
            <Toolbar />
            <Box sx={{ padding: 2 }}>{children}</Box>
          </main>
        </AppWrapper>
      </body>
    </html>
  )
}
