import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Box, Toolbar } from "@mui/material"
import MainNav from "./components/nav/MainNav"
import AppWrapper from "./components/AppWrapper"
import { ReduxProvider } from "@/store/provider"

const inter = Inter({ subsets: ["latin"] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ReduxProvider>
          <AppWrapper>
            <MainNav />
            <main>
              <Box sx={{ padding: 2 }}>{children}</Box>
            </main>
          </AppWrapper>
        </ReduxProvider>
      </body>
    </html>
  )
}
